version: "3.9"

services:
  mysql:
    build:
      context: ./mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storefront
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      
  storefront-app:
    build:
      context: .
    image: storefront-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql   