version: '3'

services:
  mysql:
    image: reubenjohn/storefront-db:v1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storefront
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  storefront-app:
    image: reubensjohn/storefront-app:v1.0
    depends_on:
      - mysql
    ports:
      - "8080:8080"
